@endpoint = 127.0.0.1:5100
@shipment-id = 3c347bac-699a-4833-9a66-1242146f72b4

### POST /shipment

POST http://{{endpoint}}/shipment
Content-Type: application/json

### GET /shipment/{shipmentId}

GET http://{{endpoint}}/shipment/{{shipment-id}}
Content-Type: application/json

### DELETE /shipment/{shipmentId}

DELETE http://{{endpoint}}/shipment/{{shipment-id}}
Content-Type: application/json

### START /shipment/{shipmentId}/start

POST http://{{endpoint}}/shipment/{{shipment-id}}/start
Content-Type: application/json
