//@endpoint = 127.0.0.1:5100
@endpoint = 127.0.0.1:55552
@shipment-id = 68bd3bad-d343-4663-841b-5e2d42165bf1

### POST /shipment

POST http://{{endpoint}}/shipment
Content-Type: application/json

### GET /shipment/{shipmentId}

GET http://{{endpoint}}/shipment/{{shipment-id}}
Content-Type: application/json

### DELETE /shipment/{shipmentId}

DELETE http://{{endpoint}}/shipment/{{shipment-id}}
Content-Type: application/json

### START /shipment/{shipmentId}/start

POST http://{{endpoint}}/shipment/{{shipment-id}}/start
Content-Type: application/json
