apiVersion: apps/v1
kind: Deployment
metadata:
  name: path-handler
  namespace: vehicle-tracker
  labels:
    app: path-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: path-handler
  template:
    metadata:
      labels:
        app: path-handler
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "path-handler"
        dapr.io/app-port: "80"
        dapr.io/config: "vtd.config"
    spec:
      containers:
        - name: path-handler
          image: "rochabr/path-handler:0.1.1"
          env:
          - name: APP_PORT
            value: "80"
          - name: PATH_FILENAME
            value: "paths/path.json"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            failureThreshold: 6
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 12
            periodSeconds: 10