apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vtd.pubsub
  namespace: vehicle-tracker
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: allowedTopics
    value: "shipments,locations"
  - name: publishingScopes
    value: "vehicle-actor=locations"
  - name: subscriptionScopes
    value: "location-handler=locations"  
scopes:
  - location-handler
  - vehicle-actor
  - front-end