# apiVersion: dapr.io/v1alpha1
# kind: Subscription
# metadata:
#   name: vtd.subscription.routes
# spec:
#   topic: routes
#   route: /routes
#   pubsubname: vtd.pubsub
# scopes:
#   - location-handler