apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vtd.location.state
  namespace: vehicle-tracker
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
scopes:
  - location-handler
  - vehicle-tracker