apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vtd.pubsub
  namespace: vehicle-tracker
spec:
  type: pubsub.kafka
  version: v1  
  metadata:
  - name: brokers
    value: kafka.kafka.svc.cluster.local:9092
  - name: authType
    value: "password"
  - name: saslUsername
    value: "user1"
  - name: saslPassword
    secretKeyRef:
      name: kafka-password
      key: kafka-password
  - name: disableTls 
    value: "true"
  - name: allowedTopics
    value: "shipments,locations"
  - name: publishingScopes
    value: "shipment-handler=shipments;vehicle-actor=locations"
  - name: subscriptionScopes
    value: "vehicle-actor=shipments;location-handler=locations"  
scopes:
  - location-handler
  - shipment-handler
  - vehicle-actor