apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: vtd.config
  namespace: vehicle-tracker
spec:
  features:
  - name: HotReload
    enabled: true
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.zipkin.svc.cluster.local:9411/api/v2/spans"
  metric:
    enabled: true